# 1. 데이터 가져오기

In [1]:
import pandas as pd
import re

In [51]:
review4us = pd.read_csv("자사리뷰.csv")
review4rivals = pd.read_csv("경쟁사리뷰.csv")

review4us.tail(100)

,Unnamed: 0,title,rating,date,time,view,text,naver,photo
27119,27119,만족,5점,2018-08-26,02:21:43,17,만족합니다,1,0
27120,27120,보통,3점,2018-08-25,02:34:32,18,"먹은지 일주일이지만, 아직은 잘 모르겠어요!",1,0
27121,27121,만족,5점,2018-08-25,02:23:30,20,더 먹어봐야 알겟지만 좋은거같아요,1,0
27122,27122,만족,5점,2018-08-25,02:23:30,17,좋네요오오오ㅎㅎㅇㅋ오 ㅎㅎ,1,0
27123,27123,보통,3점,2018-08-24,02:49:49,16,계속 먹어보면 알겠죠 아직은 별효과업근긋,1,0
...,...,...,...,...,...,...,...,...,...
27214,27214,만족,5점,2018-07-11,02:24:45,7,개별포장 편하고 좋네요,1,0
27215,27215,만족,5점,2018-07-07,02:41:20,8,여자친구님께서 매우 만족하셨습니다.,1,0
27216,27216,만족,5점,2018-07-02,02:38:11,33,좋은구성이네요 효과봤으면 좋겠네요,1,0
27217,27217,만족,5점,2018-06-27,02:56:11,34,이제받았어요,1,0
27218,27218,만족,5점,2018-06-26,02:29:45,35,배송이 좀 늦었어요...ㅠㅠ\n원하는 날부터 시작은 못했지만 기대해봅니다ㅎㅎ,1,0

In [43]:
review4rivals.tail(100)

,Unnamed: 0,date,item,text,rating,user_name,photo,one_month,repurchase,pre_reviewed
36297,36297,17.08.03.,★상품명 반드시 확인必★: 01 온가족 유산균 락토핏 골드 1통,직접 먹어본 후 부모님께 사드렸어요 변비뿐만 아니라 면역력에도 좋다고 해서 제가 직...,5,mink****,0,0,0,0
36298,36298,17.08.03.,★상품명 반드시 확인必★: 01 온가족 유산균 락토핏 골드 1통,제가 직접 먹어본 후 효과 좋아서 부모님께도 사드렸어요~,5,mink****,0,0,0,0
36299,36299,17.08.02.,★상품명 반드시 확인必★: 01 온가족 유산균 락토핏 골드 1통,빨리와서좋아용,3,rlat****,0,0,0,0
36300,36300,17.08.02.,★상품명 반드시 확인必★: 01 온가족 유산균 락토핏 골드 1통,좋아요 배송도 빠르고 늘 먹고있엉ㅅ,5,aroh****,0,0,0,0
36301,36301,17.08.02.,★상품명 반드시 확인必★: 01 온가족 유산균 락토핏 골드 1통,좋습니다ㅎ 벌써 3번째 구입이네요ㅎㅎ\n이거먹고는 매일 화장실가고있어요 매일 한개씩...,5,alsd****,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
36392,36392,17.05.22.,선택1: 락토핏 코스트코 생유산균19 1통,잘먹을게요~^^ 배송이 빨라서 너무 만족합니당ㅎㅎ,5,ayh6****,0,0,0,0
36393,36393,17.05.20.,선택1: 락토핏 생유산균 골드 1통,좋은 상품감사합니다\n빠른배송에\n잘챙겨먹으려고요\n또 구매할게요\n많이파세요^^,5,8495****,0,0,0,0
36394,36394,17.05.19.,선택1: 락토핏 생유산균 골드 1통,다들잘먹네요,5,ll97****,0,0,0,0
36395,36395,17.05.19.,선택1: 락토핏 코스트코 생유산균19 1통,빠른 배송 감사드려요,5,youn****,0,0,0,0
36396,36396,17.05.18.,선택1: 락토핏 생유산균 골드 1통,쪼아영 ㅎㅋ,5,zhen****,0,0,0,0

In [52]:
#unnamed는 필요없는 열이므로 제거한다
del review4rivals['Unnamed: 0']
del review4us['Unnamed: 0']

# Unnamed 열이 사라졌음을 볼 수 있다. 
print(review4rivals.columns, review4us.columns)

Index(['date', 'item', 'text', 'rating', 'user_name', 'photo', 'one_month',
       'repurchase', 'pre_reviewed'],
      dtype='object') Index(['title', 'rating', 'date', 'time', 'view', 'text', 'naver', 'photo'], dtype='object')

# 2. 분석 전 데이터 전처리 
* review4rivlas 의 item 종류에 각종 특수문자, 의미없는 숫자 제거하기. 
- https://regexr.com/ 이 사이트를 이용하면 정규표현식을 그나마 손쉽게 try out 할 수 있다. 
* text colum에 있는 특수문자들 제거하기. 
* unnamed column은 뭐지?

In [49]:
# item 종류에 있는 각종 특수문자와 의미없는 문자 제거하기 : ': 세미콜론 기준 왼쪽에 있는 글자는 다 없애자.  
def modify1(item):
    x=re.sub(r'[^.]*:([^ ]*)', '', str(item))     ## 이거 알아내는데 5시간 걸렸다.. 실환가?
    return(x)   

review4rivals['item'] = review4rivals['item'].apply(modify1)


def modify2(item):                    # 특수문자 제거 
    x=re.sub(r'[^\s\w]','',str(item))               
    return(x)
review4rivals['item'] = review4rivals['item'].apply(modify2)

def modify3(item):                   #락토핏 앞에 거슬렸던 2, 9, 3과 같은 숫자들이 사라진다. 
    x=re.sub('\d\d*.?(락토핏)','락토핏',str(item))
    return(x)
review4rivals['item'] = review4rivals['item'].apply(modify3)

def modify4(item):
    x=re.sub('\d\d?\d?[가-힣]','',str(item))     # 몇통, 몇포와 같은 수량정보를 제거한다.
    return(x)
review4rivals['item'] = review4rivals['item'].apply(modify4)

In [53]:
review4rivals['item'].tail(100)

36297    ★상품명 반드시 확인必★: 01 온가족 유산균 락토핏 골드 1통
36298    ★상품명 반드시 확인必★: 01 온가족 유산균 락토핏 골드 1통
36299    ★상품명 반드시 확인必★: 01 온가족 유산균 락토핏 골드 1통
36300    ★상품명 반드시 확인必★: 01 온가족 유산균 락토핏 골드 1통
36301    ★상품명 반드시 확인必★: 01 온가족 유산균 락토핏 골드 1통
                        ...
36392                선택1: 락토핏 코스트코 생유산균19 1통
36393                    선택1: 락토핏 생유산균 골드 1통
36394                    선택1: 락토핏 생유산균 골드 1통
36395                선택1: 락토핏 코스트코 생유산균19 1통
36396                    선택1: 락토핏 생유산균 골드 1통
Name: item, Length: 100, dtype: object

In [48]:
review4rivals.item.tail(100)

36297     01 온가족 유산균 락토핏 골드
36298     01 온가족 유산균 락토핏 골드
36299     01 온가족 유산균 락토핏 골드
36300     01 온가족 유산균 락토핏 골드
36301     01 온가족 유산균 락토핏 골드
                ...
36392       락토핏 코스트코 생유산균19
36393           락토핏 생유산균 골드
36394           락토핏 생유산균 골드
36395       락토핏 코스트코 생유산균19
36396           락토핏 생유산균 골드
Name: item, Length: 100, dtype: object